### ISSUE TITLE
Too many items in the feed causing a 500 error

### ISSUE THREAD

**Issue by Chris-CWZ** [spatie/laravel-feed#134]
Is nobody else having an issue with the loading time of the /feed page? I have a website that has over 5000 publications, and everytime I try to visit the feed page that's supposed to render the XML document, it just keeps telling me that the server is unable to handle this request. I suspect it could be due to the fact that there are too many things to render in the XML? Is there a workaround to this problem? Perhaps like a pagination or something?

**Comment by abr4xas** [comment]
Hi @Chris-CWZ 

No, you cant use pagination because:

```php
TypeError
Return value of Spatie\Feed\Http\FeedController::resolveFeedItems() 
must be an instance of Illuminate\Support\Collection, instance of 
Illuminate\Pagination\LengthAwarePaginator returned 
```

I think you can implement this:

Create a scope filter like this:

```php
// your model
public function scopeFilter($query, $filters)
{
    if (isset($filters['year'])) {
        if ($year = $filters['year']) {
            $query->whereYear('created_at', $year);
        }
    }
}

public static function getFeedItems()
{
   return NewsItem::filter(request(['year']))
	->latest()
	->get();
}
```

Then you can filter your post by year like this: `http://localhost/feed?year=2019`

Or, you can query your post counting a year starting from today. Don't know if this makes sense to you.

**Comment by abr4xas** [comment]
Hi @Chris-CWZ 

No, you cant use pagination because:

```php
TypeError
Return value of Spatie\Feed\Http\FeedController::resolveFeedItems() 
must be an instance of Illuminate\Support\Collection, instance of 
Illuminate\Pagination\LengthAwarePaginator returned 
```

I think you can implement this:

Create a scope filter like this:

```php
// your model
public function scopeFilter($query, $filters)
{
    if (isset($filters['year'])) {
        if ($year = $filters['year']) {
            $query->whereYear('created_at', $year);
        }
    }
}

public static function getFeedItems()
{
   return NewsItem::filter(request(['year']))
	->latest()
	->get();
}
```

Then you can filter your post by year like this: `http://localhost/feed?year=2019`

Or, you can query your post counting a year starting from today. Don't know if this makes sense to you.

**Comment by Chris-CWZ** [comment]
Hi there, really appreciate your feedback. I was just wondering if there's any way that it can return all of the publications instead of just the publications according to the year filter. But thanks for the recommendation!
