### ISSUE TITLE
Config versus Routes

### ISSUE THREAD

**Issue by danhunsaker** [spatie/laravel-feed#5]
Curious what the reasoning was behind defining feeds in a config file rather than directly in the routes file?  For example:

```php
// in your routes file
Route::feed('feed', 'All newsitems on mysite.com', 'App\NewsItem@getFeedItems');
```

I personally like keeping routes all together so I can see where each incoming request will end up without having to dig through config files elsewhere.  That also seems to be The Laravel Way™.  That said, I'm sure there was a good reason to implement it in a config file instead?

**Comment by freekmurze** [comment]
Our initial idea was that you did not have to register any routes at all. Unfortunately we found not other way then to introduce `Route::feeds();` in the routes file. 

We decided that apart from that route, it would be easier just to configure everything in one place: the config file.

If we were to make this package again, maybe we'd do it otherwise, maybe not... It's just preference I think. There's no right or wrong here.
